name: uifinal123
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/restaurant1.jpg
    - assets/images/restaurant2.jpg
    - assets/images/item1.jpg
    - assets/images/item2.jpg
    - assets/images/ravintola_yolo.jpg
    - assets/data/restaurants.json
    - assets/images/imagemenu.jpg
    - assets/images/logo.jpg
